theme = "noctalia"

[editor]
line-number = "relative"
cursorline = true
scrolloff = 5
mouse = true
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"