{ config, pkgs, caelestia, ... }: 

{
  home.username = "ciel";
  home.homeDirectory = "/home/ciel";

  # Sinkron dengan stateVersion di configuration.nix lu
  home.stateVersion = "25.11"; 

  # Tempat naruh aplikasi khusus user lu nanti
  home.packages = with pkgs; [
    # fastfetch
    # btop
    caelestia.packages.${pkgs.system}.with-shell
  ];

    wayland.windowManager.hyprland = {
    enable = true; # <-- Berdiri di sini (Sejajar dengan settings)
    xwayland.enable = true;

    settings = {
      # Di dalam settings ini KHUSUS konfigurasi murni Hyprland
      autogenerated = 0;
      monitor = ", preferred, auto, 1";

      "exec-once" = [
        "caelestia shell"
        "caelestia wallpaper set ~/Pictures/wallhaven-6omkp7.png"
      ];
    };
  };

  # Ini ditaruh di luar blok Hyprland, tapi tetep di dalam kurung kurawal utama home.nix
  # xdg.configFile."hypr/hyprland.conf".force = true;

  # --- CONFIGURATION GIT DEKLARATIF ---
  programs.git = {
    enable = true;
    userName = "mifzalpersonal";
    userEmail = "mizakigaming89@gmail.com";
    extraConfig = {
      init.defaultBranch = "main";
    };
  };

  # Aktifkan modul internal Home Manager
  programs.home-manager.enable = true;
}