"$schema" = 'https://starship.rs/config-schema.json'

# Cuma pakai 2 Tone utama: 
# Tone 1 (Accent) = color3 (Kuning/Cream M3)
# Tone 2 (Surface/Container) = color8 (Muted Surface M3)

format = """
[░▒▓](11)\
$os\
[](bg:8 fg:11)\
$directory\
$git_branch\
$git_status\
$nodejs\
$bun\
$rust\
$golang\
$php\
$time\
[ ](fg:8)\
\n$character"""

[os]
style = "bg:11 fg:0"
format = "[ $symbol ]($style)"
disabled = false

[directory]
style = "fg:15 bg:8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:8"
format = '[[ $symbol $branch ](fg:11 bg:8)]($style)'

[git_status]
style = "bg:8"
format = '[[($all_status$ahead_behind )](fg:11 bg:8)]($style)'

[nodejs]
symbol = ""
style = "bg:8"
format = '[[ $symbol ($version) ](fg:11 bg:8)]($style)'

[bun]
symbol = ""
style = "bg:8"
format = '[[ $symbol ($version) ](fg:11 bg:8)]($style)'

[rust]
symbol = ""
style = "bg:8"
format = '[[ $symbol ($version) ](fg:11 bg:8)]($style)'

[golang]
symbol = ""
style = "bg:8"
format = '[[ $symbol ($version) ](fg:11 bg:8)]($style)'

[php]
symbol = ""
style = "bg:8"
format = '[[ $symbol ($version) ](fg:11 bg:8)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:8"
format = '[[  $time ](fg:15 bg:8)]($style)'

[os.symbols]
NixOS = ""     # Symbol NixOS
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
